#include "cppdefs.h"
      SUBROUTINE get_data (ng)
!
!svn $Id$
!================================================== Hernan G. Arango ===
!  Copyright (c) 2002-2011 The ROMS/TOMS Group                         !
!    Licensed under a MIT/X style license                              !
!    See License_ROMS.txt                                              !
!=======================================================================
!                                                                      !
!  This routine reads in forcing, climatology and other data from      !
!  NetCDF files.  If there is more than one time-record,  data is      !
!  loaded into global  two-time  record arrays. The interpolation      !
!  is carried elsewhere.                                               !
!                                                                      !
!  Currently, this routine is only executed in serial mode by the      !
!  main thread.                                                        !
!                                                                      !
!=======================================================================
!
      USE mod_param
#if defined BEST_NPZ || defined BIO_GOANPZ
      USE mod_biology
#endif
      USE mod_boundary
#ifdef CLIMATOLOGY
      USE mod_clima
#endif
      USE mod_forces
      USE mod_grid
      USE mod_iounits
      USE mod_ncparam
#if defined NLM_OUTER || defined TLM_CHECK || defined TL_W4DPSAS || \
    defined W4DPSAS   || defined W4DPSAS_SENSITIVITY
      USE mod_ocean
#endif
      USE mod_scalars
#if defined UV_PSOURCE || defined TS_PSOURCE || defined Q_PSOURCE
      USE mod_sources
#endif
      USE mod_stepping
!
      implicit none
!
!  Imported variable declarations.
!
      integer, intent(in) :: ng
!
!  Local variable declarations.
!
      logical, dimension(3) :: update =                                 &
     &         (/ .FALSE., .FALSE., .FALSE. /)

#ifdef OBC
      integer :: ILB, IUB, JLB, JUB
#endif
      integer :: LBi, UBi, LBj, UBj
      integer :: i

#ifdef OBC
!
!  Lower and upper bounds for nontiled boundary arrays.
!
      ILB=LOWER_BOUND_I
      IUB=UPPER_BOUND_I
      JLB=LOWER_BOUND_J
      JUB=UPPER_BOUND_J
#endif
!
!  Lower and upper bounds for tiled arrays.
!
      LBi=LBOUND(GRID(ng)%h,DIM=1)
      UBi=UBOUND(GRID(ng)%h,DIM=1)
      LBj=LBOUND(GRID(ng)%h,DIM=2)
      UBj=UBOUND(GRID(ng)%h,DIM=2)

#ifdef PROFILE
!
!-----------------------------------------------------------------------
!  Turn on input data time wall clock.
!-----------------------------------------------------------------------
!
      CALL wclock_on (ng, iNLM, 3)
#endif
#ifdef FRC_FILE
!
!=======================================================================
!  Read in forcing data from FORCING NetCDF file.
!=======================================================================
!
#endif
#if !defined ANA_PSOURCE && (defined UV_PSOURCE || \
                             defined TS_PSOURCE || defined Q_PSOURCE)
!
!-----------------------------------------------------------------------
!  Point Sources/Sinks time dependent data.
!-----------------------------------------------------------------------
!
# if defined UV_PSOURCE || defined Q_PSOURCE
!
!  Point Source/Sink vertically integrated mass transport.
!
      CALL get_ngfld (ng, iNLM, idRtra, ncFRCid(idRtra,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                1, Nsrc(ng), 1, 2, 1, Nsrc(ng), 1,                &
     &                SOURCES(ng) % QbarG(1,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if defined TS_PSOURCE && defined SOLVE3D
!
!  Tracer Sources/Sinks.
!
      DO i=1,NT(ng)
        IF (LtracerSrc(i,ng)) THEN
          CALL get_ngfld (ng, iNLM, idRtrc(i), ncFRCid(idRtrc(i),ng),   &
     &                    nFfiles(ng), FRC(1,ng), update(1),            &
     &                    1, Nsrc(ng), N(ng), 2, 1, Nsrc(ng), N(ng),    &
     &                    SOURCES(ng) % TsrcG(1,1,1,i))
          IF (exit_flag.ne.NoError) RETURN
        END IF
      END DO
# endif
#endif

#if !defined ANA_NCEP && defined NCEP_FLUXES
!
!  Surface wind stress components.
!
      CALL get_2dfld (ng, iNLM, idUnms, ncFRCid(idUnms,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1)                 &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % nustrG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
      CALL get_2dfld (ng, iNLM, idVnms, ncFRCid(idVnms,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1)                 &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % nvstrG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Cloud fraction.
!
      CALL get_2dfld (ng, iNLM, idCfra, ncFRCid(idCfra,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % cloudG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Surface solar shortwave radiation.
!
      CALL get_2dfld (ng, iNLM, idSrad, ncFRCid(idSrad,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % srflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Surface net longwave radiation.
!
      CALL get_2dfld (ng, iNLM, idLrad, ncFRCid(idLrad,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % lrflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Net sensible heat flux
!
      CALL get_2dfld (ng, iNLM, idShea, ncFRCid(idShea,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % shflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Net latent heat flux
!
      CALL get_2dfld (ng, iNLM, idLhea, ncFRCid(idLhea,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % lhflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Surface air pressure.
!
      CALL get_2dfld (ng, iNLM, idPair, ncFRCid(idPair,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % PairG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Rainfall
!
      CALL get_2dfld (ng, iNLM, idrain, ncFRCid(idrain,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % rainG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Skin temperature
!
      CALL get_2dfld (ng, iNLM, idSkt, ncFRCid(idSkt,ng),               &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % sktG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
!  Observed (NCEP) ice concentration
!
      CALL get_2dfld (ng, iNLM, idIcec, ncFRCid(idIcec,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % icecG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
!
# if !defined ANA_RUNOFF && defined RUNOFF
!
!-----------------------------------------------------------------------
!  Surface runoff rate
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idRunoff, ncFRCid(idRunoff,ng),         &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % runoffG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

#endif

#if !defined ANA_WINDS && (defined BULK_FLUXES || defined ECOSIM)
!
!-----------------------------------------------------------------------
!  Surface wind components.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idUair, ncFRCid(idUair,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % UwindG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_2dfld (ng , iNLM, idVair, ncFRCid(idVair,ng),            &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % VwindG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
#endif

#if !defined AIR_OCEAN && !defined NCEP_FLUXES
# if !defined ANA_SMFLUX && !defined BULK_FLUXES && !defined ANA_NCEP
!
!-----------------------------------------------------------------------
!  Surface wind stress components.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idUsms, ncFRCid(idUsms,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % umask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % sustrG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_2dfld (ng, iNLM, idVsms, ncFRCid(idVsms,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % vmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % svstrG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if defined FOUR_DVAR && defined BULK_FLUXES && defined NL_BULK_FLUXES
!
!-----------------------------------------------------------------------
!  If not first NLM run, get surface wind stress components from initial
!  NLM run.
!-----------------------------------------------------------------------
!
      IF (Nrun.gt.1) THEN
        CALL get_2dfld (ng, iNLM, idUsms, BLK(ng)%ncid,                 &
     &                  1, BLK(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#  ifdef MASKING
     &                  GRID(ng) % umask(LBi,LBj),                      &
#  endif
     &                  FORCES(ng) % sustrG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN

        CALL get_2dfld (ng, iNLM, idVsms, BLK(ng)%ncid,                 &
     &                  1, BLK(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#  ifdef MASKING
     &                  GRID(ng) % vmask(LBi,LBj),                      &
#  endif
     &                  FORCES(ng) % svstrG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN
      END IF
# endif
#endif

#ifdef SOLVE3D

# if !defined ANA_SSSFLX && defined SSSFLX
      CALL get_2dfld (ng, iNLM, idSSSf, ncFRCid(idSSSf,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),            &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#   ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#   endif
     &                FORCES(ng) % sssflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_FASTICE && defined FASTICE_CLIMATOLOGY
      CALL get_2dfld (ng, iNLM, idFastIce, ncFRCid(idFastIce,ng),       &
     &                nFfiles(ng), FRC(1,ng), update(1),            &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#   ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#   endif
     &                FORCES(ng) % fastice_clmG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif
#endif

#if !defined ANA_PAIR && (defined BULK_FLUXES || defined ECOSIM || \
                          defined ATM_PRESS)
!
!-----------------------------------------------------------------------
!  Surface air pressure.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idPair, ncFRCid(idPair,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
# ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
# endif
     &                FORCES(ng) % PairG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
#endif

#if !defined ANA_WWAVE && defined WAVE_DATA
!
!-----------------------------------------------------------------------
!  Surface wind induced wave amplitude, direction and period.
!-----------------------------------------------------------------------
!
# ifdef WAVES_DIR
      CALL get_2dfld (ng, iNLM, idWdir, ncFRCid(idWdir,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % DwaveG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# ifdef WAVES_HEIGHT
      CALL get_2dfld (ng, iNLM, idWamp, ncFRCid(idWamp,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % HwaveG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# ifdef WAVES_LENGTH
      CALL get_2dfld (ng, iNLM, idWlen, ncFRCid(idWlen,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % LwaveG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# ifdef WAVES_TOP_PERIOD
      CALL get_2dfld (ng, iNLM, idWptp, ncFRCid(idWptp,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % Pwave_topG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# ifdef WAVES_BOT_PERIOD
      CALL get_2dfld (ng, iNLM, idWpbt, ncFRCid(idWpbt,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % Pwave_botG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if defined WAVES_UB
      CALL get_2dfld (ng, iNLM, idWorb, ncFRCid(idWorb,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % Ub_swanG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if defined TKE_WAVEDISS
      CALL get_2dfld (ng, iNLM, idWdis, ncFRCid(idWdis,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % Wave_dissipG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if defined SVENDSEN_ROLLER
      CALL get_2dfld (ng, iNLM, idWbrk, ncFRCid(idWbrk,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % Wave_breakG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif
#endif

#ifdef SOLVE3D

# if !defined ANA_CLOUD && defined CLOUDS
!
!-----------------------------------------------------------------------
!  Cloud fraction.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idCfra, ncFRCid(idCfra,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % cloudG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_SRFLUX && defined SHORTWAVE && !defined ANA_NCEP
!
!-----------------------------------------------------------------------
!  Surface solar shortwave radiation.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idSrad, ncFRCid(idSrad,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % srflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if defined BULK_FLUXES && !defined LONGWAVE && !defined LONGWAVE_OUT
!
!-----------------------------------------------------------------------
!  Surface net longwave radiation.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idLrad, ncFRCid(idLrad,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % lrflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if defined BULK_FLUXES && defined LONGWAVE_OUT
!
!-----------------------------------------------------------------------
!  Surface downwelling longwave radiation.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idLdwn, ncFRCid(idLdwn,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % lrflxG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_TAIR && \
    ( defined BULK_FLUXES || defined ECOSIM || \
     (defined SHORTWAVE && defined ANA_SRFLUX && defined ALBEDO) )
!
!-----------------------------------------------------------------------
!  Surface air temperature.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idTair, ncFRCid(idTair,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % TairG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_HUMIDITY && \
     (defined BULK_FLUXES || defined ECOSIM || \
     (defined SHORTWAVE && defined ANA_SRFLUX && defined ALBEDO) )

!
!-----------------------------------------------------------------------
!  Surface air humidity.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idQair, ncFRCid(idQair,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % HairG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_RAIN && defined BULK_FLUXES
!
!-----------------------------------------------------------------------
!  Rain fall rate.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idrain, ncFRCid(idrain,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % rainG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_RUNOFF && defined BULK_FLUXES && defined RUNOFF
!
!-----------------------------------------------------------------------
!  Surface runoff rate
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idRunoff, ncFRCid(idRunoff,ng),         &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % runoffG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_STFLUX && !defined BULK_FLUXES && !defined NCEP_FLUXES
!
!-----------------------------------------------------------------------
!  Surface net heat flux.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idTsur(itemp),                          &
     &                ncFRCid(idTsur(itemp),ng),                        &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % stflxG(LBi,LBj,1,itemp))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_STFLUX  && defined FOUR_DVAR      && \
      defined BULK_FLUXES && defined NL_BULK_FLUXES
!
!-----------------------------------------------------------------------
!  If not first NLM run, get surface net heat flux from initial NLM run.
!-----------------------------------------------------------------------
!
      IF (Nrun.gt.1) THEN
        CALL get_2dfld (ng, iNLM, idTsur(itemp), BLK(ng)%ncid,          &
     &                  1, BLK(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#  ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
#  endif
     &                  FORCES(ng) % stflxG(LBi,LBj,1,itemp))
        IF (exit_flag.ne.NoError) RETURN
      END IF
# endif

# if !defined ANA_SST && defined QCORRECTION && !defined NCEP_FLUXES
!
!-----------------------------------------------------------------------
!  Surface net heat flux correction fields: sea surface temperature
!  (SST) and heat flux sensitivity to SST (dQdSST).
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idSSTc, ncFRCid(idSSTc,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % sstG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_2dfld (ng, iNLM, iddQdT, ncFRCid(iddQdT,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % dqdtG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# ifndef ANA_BTFLUX
!
!-----------------------------------------------------------------------
!  Bottom net heat flux.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idTbot(itemp),                          &
     &                ncFRCid(idTbot(itemp),ng),                        &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                FORCES(ng) % btflxG(LBi,LBj,1,itemp))
      IF (exit_flag.ne.NoError) RETURN
# endif

# ifdef SALINITY
#  if defined NL_BULK_FLUXES && !defined BULK_FLUXES
!
!-----------------------------------------------------------------------
!  Surface net freshwater flux (E-P) from NLM bulk flux computation.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iRPM, idEmPf, ncFRCid(idEmPf,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#   ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#   endif
     &                FORCES(ng) % stflxG(LBi,LBj,1,isalt))
      IF (exit_flag.ne.NoError) RETURN

#  elif !(defined ANA_SSFLUX || defined EMINUSP || defined SRELAXATION)
!
!-----------------------------------------------------------------------
!  Surface net freshwater flux: E-P.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idsfwf, ncFRCid(idsfwf,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#   ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#   endif
     &                FORCES(ng) % stflxG(LBi,LBj,1,isalt))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  if !defined ANA_STFLUX  && defined FOUR_DVAR      && \
       defined BULK_FLUXES && defined NL_BULK_FLUXES && \
       defined EMINUSP
!
!-----------------------------------------------------------------------
!  If not first NLM run, get freshwater flux (E-P) from initial NLM run.
!-----------------------------------------------------------------------
!
      IF (Nrun.gt.1) THEN
        CALL get_2dfld (ng, iNLM, idEmPf, BLK(ng)%ncid,                 &
     &                  1, BLK(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#   ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
#   endif
     &                  FORCES(ng) % stflxG(LBi,LBj,1,isalt))
        IF (exit_flag.ne.NoError) RETURN
      END IF
#  endif

#  if !defined ANA_SSS && (defined SCORRECTION || defined SRELAXATION)
!
!-----------------------------------------------------------------------
!  Surface net freshwater flux correction field: sea surface salinity.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idSSSc, ncFRCid(idSSSc,ng),             &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#   ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#   endif
     &                FORCES(ng) % sssG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  ifndef ANA_BSFLUX
!
!-----------------------------------------------------------------------
!  Bottom net freshwater flux.
!-----------------------------------------------------------------------
!
      CALL get_2dfld (ng, iNLM, idTbot(isalt),                          &
     &                ncFRCid(idTbot(isalt),ng),                        &
     &                nFfiles(ng), FRC(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#   ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#   endif
     &                FORCES(ng) % btflxG(LBi,LBj,1,isalt))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif

# if defined SEDIMENT || defined BIOLOGY
#  ifndef ANA_SPFLUX
!
!-----------------------------------------------------------------------
!  Passive tracers surface fluxes.
!-----------------------------------------------------------------------
!
      DO i=NAT+1,NT(ng)
        CALL get_2dfld (ng, iNLM, idTsur(i), ncFRCid(idTsur(i),ng),     &
     &                  nFfiles(ng), FRC(1,ng), update(1),              &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#   ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
#   endif
     &                  FORCES(ng) % stflxG(LBi,LBj,1,i))
        IF (exit_flag.ne.NoError) RETURN
      END DO
#  endif

#  ifndef ANA_BPFLUX
!
!-----------------------------------------------------------------------
!  Passive tracers bottom fluxes.
!-----------------------------------------------------------------------
!
      DO i=NAT+1,NT(ng)
        CALL get_2dfld (ng, iNLM, idTbot(i), ncFRCid(idTbot(i),ng),     &
     &                  nFfiles(ng), FRC(1,ng), update(1),              &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#   ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
#   endif
     &                  FORCES(ng) % btflxG(LBi,LBj,1,i))
        IF (exit_flag.ne.NoError) RETURN
      END DO
#  endif
# endif
#endif

#ifdef OBC_DATA
!
!=======================================================================
!  Read in open boundary conditions from BOUNDARY NetCDF file.
!=======================================================================
!
# ifndef ANA_FSOBC
#  ifdef WEST_FSOBC
      CALL get_ngfld (ng, iNLM, idZbry(iwest), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % zetaG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  ifdef EAST_FSOBC
      CALL get_ngfld (ng, iNLM, idZbry(ieast), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % zetaG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  ifdef SOUTH_FSOBC
      CALL get_ngfld (ng, iNLM, idZbry(isouth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % zetaG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  ifdef NORTH_FSOBC
      CALL get_ngfld (ng, iNLM, idZbry(inorth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % zetaG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif

# ifndef ANA_M2OBC
#  ifdef WEST_M2OBC
      CALL get_ngfld (ng, iNLM, idU2bc(iwest), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % ubarG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV2bc(iwest), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, 1, 2, 1, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % vbarG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  ifdef EAST_M2OBC
      CALL get_ngfld (ng, iNLM, idU2bc(ieast), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % ubarG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV2bc(ieast), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, 1, 2, 1, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % vbarG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  ifdef SOUTH_M2OBC
      CALL get_ngfld (ng, iNLM, idU2bc(isouth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, 1, 2, 1, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % ubarG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV2bc(isouth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % vbarG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  ifdef NORTH_M2OBC
      CALL get_ngfld (ng, iNLM, idU2bc(inorth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, 1, 2, 1, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % ubarG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV2bc(inorth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % vbarG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
#ifdef ICE_MODEL
# ifndef ANA_MIOBC
#  ifdef WEST_MIOBC
      CALL get_ngfld (ng, iNLM, idUibc(iwest), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % uiG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
      CALL get_ngfld (ng, iNLM, idVibc(iwest), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 1, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % viG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_MIOBC
      CALL get_ngfld (ng, iNLM, idUibc(ieast), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % uiG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
      CALL get_ngfld (ng, iNLM, idVibc(ieast), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 1, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % viG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_MIOBC
      CALL get_ngfld (ng, iNLM, idUibc(isouth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 1, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % uiG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
      CALL get_ngfld (ng, iNLM, idVibc(isouth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % viG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_MIOBC
      CALL get_ngfld (ng, iNLM, idUibc(inorth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 1, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % uiG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
      CALL get_ngfld (ng, iNLM, idVibc(inorth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % viG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_AIOBC
#  ifdef WEST_AIOBC
      CALL get_ngfld (ng, iNLM, idAibc(iwest), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % aiG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_AIOBC
      CALL get_ngfld (ng, iNLM, idAibc(ieast), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % aiG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_AIOBC
      CALL get_ngfld (ng, iNLM, idAibc(isouth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % aiG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_AIOBC
      CALL get_ngfld (ng, iNLM, idAibc(inorth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % aiG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif

# ifndef ANA_HIOBC
#  ifdef WEST_HIOBC
      CALL get_ngfld (ng, iNLM, idHibc(iwest), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hiG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_HIOBC
      CALL get_ngfld (ng, iNLM, idHibc(ieast), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hiG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_HIOBC
      CALL get_ngfld (ng, iNLM, idHibc(isouth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hiG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_HIOBC
      CALL get_ngfld (ng, iNLM, idHibc(inorth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hiG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_HSNOBC
#  ifdef WEST_HSNOBC
      CALL get_ngfld (ng, iNLM, idHsnbc(iwest), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hsnG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_HSNOBC
      CALL get_ngfld (ng, iNLM, idHsnbc(ieast), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hsnG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_HSNOBC
      CALL get_ngfld (ng, iNLM, idHsnbc(isouth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hsnG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_HSNOBC
      CALL get_ngfld (ng, iNLM, idHsnbc(inorth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % hsnG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_TIOBC
#  ifdef WEST_TIOBC
      CALL get_ngfld (ng, iNLM, idTibc(iwest), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % tiG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_TIOBC
      CALL get_ngfld (ng, iNLM, idTibc(ieast), BRY(ng)%ncid, 1,         &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % tiG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_TIOBC
      CALL get_ngfld (ng, iNLM, idTibc(isouth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % tiG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_TIOBC
      CALL get_ngfld (ng, iNLM, idTibc(inorth), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % tiG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_SFWATOBC
#  ifdef WEST_SFWATOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(iwest), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sfwatG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_SFWATOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(ieast), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sfwatG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_SFWATOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(isouth), BRY(ng)%ncid, 1,       &
     &               BRY(ng), update(1),                                &
     &               ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                    &
     &                BOUNDARY(ng) % sfwatG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_SFWATOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(inorth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sfwatG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_AGEICEOBC
#  ifdef WEST_AGEICEOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(iwest), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % ageiceG_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_AGEICEOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(ieast), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % ageiceG_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_AGEICEOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(isouth), BRY(ng)%ncid, 1,       &
     &               BRY(ng), update(1),                                &
     &               ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                    &
     &                BOUNDARY(ng) % ageiceG_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_AGEICEOBC
      CALL get_ngfld (ng, iNLM, idSfwbc(inorth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % ageiceG_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_SIG11OBC
#  ifdef WEST_SIG11OBC
      CALL get_ngfld (ng, iNLM, idS11bc(iwest), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig11G_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_SIG11OBC
      CALL get_ngfld (ng, iNLM, idS11bc(ieast), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig11G_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_SIG11OBC
      CALL get_ngfld (ng, iNLM, idS11bc(isouth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig11G_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_SIG11OBC
      CALL get_ngfld (ng, iNLM, idS11bc(inorth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig11G_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_SIG22OBC
#  ifdef WEST_SIG22OBC
      CALL get_ngfld (ng, iNLM, idS22bc(iwest), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig22G_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_SIG22OBC
      CALL get_ngfld (ng, iNLM, idS22bc(ieast), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig22G_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_SIG22OBC
      CALL get_ngfld (ng, iNLM, idS22bc(isouth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig22G_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_SIG22OBC
      CALL get_ngfld (ng, iNLM, idS22bc(inorth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig22G_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
# ifndef ANA_SIG12OBC
#  ifdef WEST_SIG12OBC
      CALL get_ngfld (ng, iNLM, idS12bc(iwest), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig12G_west(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef EAST_SIG12OBC
      CALL get_ngfld (ng, iNLM, idS12bc(ieast), BRY(ng)%ncid, 1,        &
     &                BRY(ng), update(1),                               &
     &                JLB, JUB, 1, 2, 0, Mm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig12G_east(JLB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef SOUTH_SIG12OBC
      CALL get_ngfld (ng, iNLM, idS12bc(isouth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig12G_south(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
#  ifdef NORTH_SIG12OBC
      CALL get_ngfld (ng, iNLM, idS12bc(inorth), BRY(ng)%ncid, 1,       &
     &                BRY(ng), update(1),                               &
     &                ILB, IUB, 1, 2, 0, Lm(ng)+1, 1,                   &
     &                BOUNDARY(ng) % sig12G_north(ILB,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
#endif

# ifdef SOLVE3D
#  ifndef ANA_M3OBC
#   ifdef WEST_M3OBC
      CALL get_ngfld (ng, iNLM, idU3bc(iwest), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, N(ng), 2, 0, Mm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % uG_west(JLB,1,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV3bc(iwest), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, N(ng), 2, 1, Mm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % vG_west(JLB,1,1))
      IF (exit_flag.ne.NoError) RETURN
#   endif

#   ifdef EAST_M3OBC
      CALL get_ngfld (ng, iNLM, idU3bc(ieast), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, N(ng), 2, 0, Mm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % uG_east(JLB,1,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV3bc(ieast), BRY(ng)%ncid,            &
     &                1, BRY(ng), update(1),                            &
     &                JLB, JUB, N(ng), 2, 1, Mm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % vG_east(JLB,1,1))
      IF (exit_flag.ne.NoError) RETURN
#   endif

#   ifdef SOUTH_M3OBC
      CALL get_ngfld (ng, iNLM, idU3bc(isouth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, N(ng), 2, 1, Lm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % uG_south(ILB,1,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV3bc(isouth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, N(ng), 2, 0, Lm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % vG_south(ILB,1,1))
      IF (exit_flag.ne.NoError) RETURN
#   endif

#   ifdef NORTH_M3OBC
      CALL get_ngfld (ng, iNLM, idU3bc(inorth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, N(ng), 2, 1, Lm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % uG_north(ILB,1,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_ngfld (ng, iNLM, idV3bc(inorth), BRY(ng)%ncid,           &
     &                1, BRY(ng), update(1),                            &
     &                ILB, IUB, N(ng), 2, 0, Lm(ng)+1, N(ng),           &
     &                BOUNDARY(ng) % vG_north(ILB,1,1))
      IF (exit_flag.ne.NoError) RETURN
#   endif
#  endif

#  ifndef ANA_TOBC
#   ifdef WEST_TOBC
      DO i=1,NT(ng)
        CALL get_ngfld (ng, iNLM, idTbry(iwest,i), BRY(ng)%ncid,        &
     &                  1, BRY(ng), update(1),                          &
     &                  JLB, JUB, N(ng), 2, 0, Mm(ng)+1, N(ng),         &
     &                  BOUNDARY(ng) % tG_west(JLB,1,1,i))
        IF (exit_flag.ne.NoError) RETURN
      END DO
#   endif

#   ifdef EAST_TOBC
      DO i=1,NT(ng)
        CALL get_ngfld (ng, iNLM, idTbry(ieast,i), BRY(ng)%ncid,        &
     &                  1, BRY(ng), update(1),                          &
     &                  JLB, JUB, N(ng), 2, 0, Mm(ng)+1, N(ng),         &
     &                  BOUNDARY(ng) % tG_east(JLB,1,1,i))
        IF (exit_flag.ne.NoError) RETURN
      END DO
#   endif

#   ifdef SOUTH_TOBC
      DO i=1,NT(ng)
        CALL get_ngfld (ng, iNLM, idTbry(isouth,i), BRY(ng)%ncid,       &
     &                  1, BRY(ng), update(1),                          &
     &                  ILB, IUB, N(ng), 2, 0, Lm(ng)+1, N(ng),         &
     &                  BOUNDARY(ng) % tG_south(ILB,1,1,i))
        IF (exit_flag.ne.NoError) RETURN
      END DO
#   endif

#   ifdef NORTH_TOBC
      DO i=1,NT(ng)
        CALL get_ngfld (ng, iNLM, idTbry(inorth,i), BRY(ng)%ncid,       &
     &                  1, BRY(ng), update(1),                          &
     &                  ILB, IUB, N(ng), 2, 0, Lm(ng)+1, N(ng),         &
     &                  BOUNDARY(ng) % tG_north(ILB,1,1,i))
        IF (exit_flag.ne.NoError) RETURN
      END DO
#   endif
#  endif
# endif
#endif

#ifdef CLM_FILE
!
!=======================================================================
!  Read in climatology data from CLIMATOLOGY NetCDF file.
!=======================================================================
!
# if !defined ANA_SSH && defined ZCLIMATOLOGY
      CALL get_2dfld (ng, iNLM, idSSHc, CLM(ng)%ncid,                   &
     &                1, CLM(ng), update(1),                            &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#  endif
     &                CLIMA(ng) % sshG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# if !defined ANA_M2CLIMA && defined M2CLIMATOLOGY
      CALL get_2dfld (ng, iNLM, idUbcl, CLM(ng)%ncid,                   &
     &                1, CLM(ng), update(1),                            &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % umask(LBi,LBj),                        &
#  endif
     &                CLIMA(ng) % ubarclmG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_2dfld (ng, iNLM, idVbcl, CLM(ng)%ncid,                   &
     &                1, CLM(ng), update(1),                            &
     &                LBi, UBi, LBj, UBj, 2, 1,                         &
#  ifdef MASKING
     &                GRID(ng) % vmask(LBi,LBj),                        &
#  endif
     &                CLIMA(ng) % vbarclmG(LBi,LBj,1))
      IF (exit_flag.ne.NoError) RETURN
# endif

# ifdef SOLVE3D
#  if !defined ANA_TCLIMA && defined TCLIMATOLOGY
!  KLUDGE - how many tracers to read? It depends...
      DO i=1,NAT
        CALL get_3dfld (ng, iNLM, idTclm(i), CLM(ng)%ncid,              &
     &                  1, CLM(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,             &
#   ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
#   endif
     &                  CLIMA(ng) % tclmG(LBi,LBj,1,1,i))
        IF (exit_flag.ne.NoError) RETURN
      END DO

#   if !defined ANA_AKTCLIMA && defined AKTCLIMATOLOGY
      CALL get_3dfld (ng, iNLM, idAclm, ncCLMid(idAclm,ng),             &
     &                  nCfiles(ng), CLM(1,ng), update(1),              &
     &                  LBi, UBi, LBj, UBj, 0, N(ng), 2, 1,             &
#    ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
#    endif
     &                  CLIMA(ng) % AclmG(LBi,LBj,0,1))
      IF (exit_flag.ne.NoError) RETURN
#   endif

#   if (defined BEST_NPZ || defined BIO_GOANPZ) && defined IRON_LIMIT
      CALL get_3dfld (ng, iNLM, idTclm(iFe), ncCLMid(ng), nCfiles(ng),  &
     &                CLM(1,ng), update(1),                             &
     &                LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,               &
#    ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#    endif
     &                CLIMA(ng) % tclmG(LBi,LBj,1,1,iFe))
      IF (exit_flag.ne.NoError) RETURN
#   endif
#    if defined ICE_BIO && defined CLIM_ICE_1D
       CALL get_3dfld (ng, iNLM, idTclm(i1CI), ncCLMid(ng),             &
     &                nCfiles(ng), CLM(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,               &
#    ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#    endif
     &                CLIMA(ng) % tclmG(LBi,LBj,1,1,i1CI))
      IF (exit_flag.ne.NoError) RETURN
#   endif
#  endif
#  if !defined ANA_OCLIMA && defined OCLIMATOLOGY
      CALL get_3dfld (ng, iNLM, idOclm, ncCLMid(idOclm,ng),             &
     &                nCfiles(ng), CLM(1,ng), update(1),                &
     &                LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,               &
#    ifdef MASKING
     &                GRID(ng) % rmask(LBi,LBj),                        &
#    endif
     &                CLIMA(ng) % oclmG(LBi,LBj,1,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif

#  if !defined ANA_M3CLIMA && defined M3CLIMATOLOGY
      CALL get_3dfld (ng, iNLM, idUclm, CLM(ng)%ncid,                   &
     &                1, CLM(ng), update(1),                            &
     &                LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,               &
#   ifdef MASKING
     &                GRID(ng) % umask(LBi,LBj),                        &
#   endif
     &                CLIMA(ng) % uclmG(LBi,LBj,1,1))
      IF (exit_flag.ne.NoError) RETURN

      CALL get_3dfld (ng, iNLM, idVclm, CLM(ng)%ncid,                   &
     &                1, CLM(ng), update(1),                            &
     &                LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,               &
#   ifdef MASKING
     &                GRID(ng) % vmask(LBi,LBj),                        &
#   endif
     &                CLIMA(ng) % vclmG(LBi,LBj,1,1))
      IF (exit_flag.ne.NoError) RETURN
#  endif
# endif
#endif

#ifdef TLM_CHECK
!
!-----------------------------------------------------------------------
!  If tangent linear model check, read in nonlinear forward solution
!  to compute dot product with perturbated nonlinear solution. Time
!  interpolation between snapshot is not required (see subroutine
!  "nl_dotproduct").
!-----------------------------------------------------------------------
!
      IF (outer.ge.1) THEN
!
!  Read in free-surface.
!
        CALL get_2dfld (ng, iNLM, idFsur, FWD(ng)%ncid,                 &
     &                  1, FWD(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
# ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
# endif
     &                  OCEAN(ng) % zetaG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN
!
!  Read 2D momentum.
!
        CALL get_2dfld (ng, iNLM, idUbar, FWD(ng)%ncid,                 &
     &                  1, FWD(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
# ifdef MASKING
     &                  GRID(ng) % umask(LBi,LBj),                      &
# endif
     &                  OCEAN(ng) % ubarG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN

        CALL get_2dfld (ng, iNLM, idVbar, FWD(ng)%ncid,                 &
     &                  1, FWD(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
# ifdef MASKING
     &                  GRID(ng) % vmask(LBi,LBj),                      &
# endif
     &                  OCEAN(ng) % vbarG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN
# ifdef SOLVE3D
!
!  Read in 3D momentum.
!
        CALL get_3dfld (ng, iNLM, idUvel, FWD(ng)%ncid,                 &
     &                  1, FWD(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,             &
#  ifdef MASKING
     &                  GRID(ng) % umask(LBi,LBj),                      &
#  endif
     &                  OCEAN(ng) % uG(LBi,LBj,1,1))
        IF (exit_flag.ne.NoError) RETURN

        CALL get_3dfld (ng, iNLM, idVvel, FWD(ng)%ncid,                 &
     &                  1, FWD(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,             &
#  ifdef MASKING
     &                  GRID(ng) % vmask(LBi,LBj),                      &
#  endif
     &                  OCEAN(ng) % vG(LBi,LBj,1,1))
        IF (exit_flag.ne.NoError) RETURN
!
!  Read in 3D tracers.
!
        DO i=1,NT(ng)
          CALL get_3dfld (ng, iNLM, idTvar(i), FWD(ng)%ncid,            &
     &                    1, FWD(ng), update(1),                        &
     &                    LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,           &
#  ifdef MASKING
     &                    GRID(ng) % vmask(LBi,LBj),                    &
#  endif
     &                    OCEAN(ng) % tG(LBi,LBj,1,1,i))
          IF (exit_flag.ne.NoError) RETURN
        END DO
# endif
      END IF
#endif

#if defined NLM_OUTER || defined TL_W4DPSAS           || \
    defined W4DPSAS   || defined W4DPSAS_SENSITIVITY
!
!-----------------------------------------------------------------------
!  Read weak contraint forcing snapshots. Notice that the forward
!  basic state snapshops arrays are reused here.
!-----------------------------------------------------------------------
!
      IF (FrequentImpulse(ng)) THEN
!
!  Read in free-surface.
!
        CALL get_2dfld (ng, iNLM, idFsur, TLF(ng)%ncid,                 &
     &                  1, TLF(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
# ifdef MASKING
     &                  GRID(ng) % rmask(LBi,LBj),                      &
# endif
     &                  OCEAN(ng) % zetaG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN
# ifndef SOLVE3D
!
!  Read 2D momentum.
!
        CALL get_2dfld (ng, iNLM, idUbar, TLF(ng)%ncid,                 &
     &                  1, TLF(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#  ifdef MASKING
     &                  GRID(ng) % umask(LBi,LBj),                      &
#  endif
     &                  OCEAN(ng) % ubarG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN

        CALL get_2dfld (ng, iNLM, idVbar, TLF(ng)%ncid,                 &
     &                  1, TLF(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 2, 1,                       &
#  ifdef MASKING
     &                  GRID(ng) % vmask(LBi,LBj),                      &
#  endif
     &                  OCEAN(ng) % vbarG(LBi,LBj,1))
        IF (exit_flag.ne.NoError) RETURN
# endif
# ifdef SOLVE3D
!
!  Read in 3D momentum.
!
        CALL get_3dfld (ng, iNLM, idUvel, TLF(ng)%ncid,                 &
     &                  1, TLF(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,             &
#  ifdef MASKING
     &                  GRID(ng) % umask(LBi,LBj),                      &
#  endif
     &                  OCEAN(ng) % uG(LBi,LBj,1,1))
        IF (exit_flag.ne.NoError) RETURN

        CALL get_3dfld (ng, iNLM, idVvel, TLF(ng)%ncid,                 &
     &                  1, TLF(ng), update(1),                          &
     &                  LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,             &
#  ifdef MASKING
     &                  GRID(ng) % vmask(LBi,LBj),                      &
#  endif
     &                  OCEAN(ng) % vG(LBi,LBj,1,1))
        IF (exit_flag.ne.NoError) RETURN
!
!  Read in 3D tracers.
!
        DO i=1,NT(ng)
          CALL get_3dfld (ng, iNLM, idTvar(i), TLF(ng)%ncid,            &
     &                    1, TLF(ng), update(1),                        &
     &                    LBi, UBi, LBj, UBj, 1, N(ng), 2, 1,           &
#  ifdef MASKING
     &                    GRID(ng) % rmask(LBi,LBj),                    &
#  endif
     &                    OCEAN(ng) % tG(LBi,LBj,1,1,i))
          IF (exit_flag.ne.NoError) RETURN
        END DO
# endif
      END IF
#endif

#ifdef PROFILE
!
!-----------------------------------------------------------------------
!  Turn off input data time wall clock.
!-----------------------------------------------------------------------
!
      CALL wclock_off (ng, iNLM, 3)
#endif
      RETURN
      END SUBROUTINE get_data
